import { useEffect, useState } from 'react';
import { useParams } from 'react-router-dom';
import axios from 'axios';
import useEditorStore from '../store/useEditorStore';
import VideoPreview from '../components/VideoPreview';
import TranscriptEditor from '../components/TranscriptEditor';
import Timeline from '../components/Timeline';
import Toolbar from '../components/Toolbar';
import Sidebar from '../components/Sidebar';
import ConfirmDialog from '../components/ConfirmDialog';
import SceneDeletionOverlay from '../components/SceneDeletionOverlay';
import { parseSegmentsToWords } from '../utils/transcriptParser';

function Editor() {
  const { projectId } = useParams();
  const {
    project,
    setProject,
    selectedSceneId,
    deleteScene,
    openSceneDeleteModal,
    closeSceneDeleteModal,
    sceneDeletionModal
  } = useEditorStore();
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState(null);
  
  // ✅ NEW: Keyboard handler for Delete key (always uses latest store state)
  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.target.tagName === 'INPUT' || e.target.tagName === 'TEXTAREA') return;
      if (e.key !== 'Delete' && e.key !== 'Backspace') return;

      const { selectedSceneId: currentSceneId, openSceneDeleteModal: openModal } = useEditorStore.getState();
      if (currentSceneId) {
        e.preventDefault();
        openModal(currentSceneId);
      }
    };

    document.addEventListener('keydown', handleKeyDown, true);
    return () => document.removeEventListener('keydown', handleKeyDown, true);
  }, []);

  useEffect(() => {
    const loadProject = async () => {
      try {
        const response = await axios.get(`/api/project/${projectId}`);
        const projectData = response.data;
        
        // Ensure project has all required fields
        if (!projectData.words && projectData.transcriptionSegments) {
          // Words will be generated by the store's setProject
        }
        
        setProject(projectData);
        setLoading(false);
      } catch (err) {
        console.error('Failed to load project:', err);
        setError(err.response?.data?.error || 'Failed to load project');
        setLoading(false);
      }
    };

    if (projectId) {
      loadProject();
    }
  }, [projectId, setProject]);

  if (loading) {
    return (
      <div className="h-screen flex items-center justify-center">
        <div className="text-center">
          <div className="animate-spin rounded-full h-12 w-12 border-b-2 border-primary-600 mx-auto mb-4"></div>
          <p className="text-gray-600">Loading project...</p>
        </div>
      </div>
    );
  }

  if (error) {
    return (
      <div className="h-screen flex items-center justify-center">
        <div className="text-center">
          <p className="text-red-600 mb-4">{error}</p>
          <a href="/" className="btn btn-primary">Back to Home</a>
        </div>
      </div>
    );
  }

  if (!project) {
    return null;
  }

  return (
    <div className="h-screen flex flex-col bg-white">
      <Toolbar />
      
      <SceneDeletionOverlay />
      <ConfirmDialog
        isOpen={sceneDeletionModal.isOpen}
        title="Delete scene"
        message="Deleting a scene will remove it from the video and regenerate the timeline. This action cannot be undone."
        confirmLabel="Delete scene"
        cancelLabel="Cancel"
        isDanger
        onCancel={closeSceneDeleteModal}
        onConfirm={() => {
          deleteScene(sceneDeletionModal.sceneId);
          closeSceneDeleteModal();
        }}
      />

      <div className="flex-1 flex overflow-hidden bg-white">
        {/* Left Panel - Transcript Editor */}
        <div className="w-72 border-r border-gray-200 flex flex-col bg-white overflow-hidden">
          <TranscriptEditor />
        </div>

        {/* Center Panel - Video Preview & Timeline */}
        <div className="flex-1 flex flex-col min-w-0 bg-gray-100">
          {/* Top center header with Write button */}
          <div className="h-12 bg-white border-b border-gray-200 flex items-center justify-between px-4">
            <div className="flex items-center space-x-4">
              <button className="flex items-center space-x-2 text-sm text-gray-700 hover:bg-gray-100 px-3 py-1 rounded">
                <svg className="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M11 5H6a2 2 0 00-2 2v11a2 2 0 002 2h11a2 2 0 002-2v-5m-1.414-9.414a2 2 0 112.828 2.828L11.828 15H9v-2.828l8.586-8.586z" />
                </svg>
                <span>Write</span>
              </button>
              <button className="p-1.5 text-gray-600 hover:bg-gray-100 rounded">
                <svg className="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
                  <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M4 16l4.586-4.586a2 2 0 012.828 0L16 16m-2-2l1.586-1.586a2 2 0 012.828 0L20 14m-6-6h.01M6 20h12a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v12a2 2 0 002 2z" />
                </svg>
              </button>
            </div>
          </div>

          {/* Video Preview */}
          <div className="flex-1 flex flex-col min-h-0 bg-gray-900">
            <VideoPreview />
          </div>

          {/* Video settings tabs */}
          <div className="h-10 bg-white border-t border-gray-200 flex items-center px-4 space-x-4 text-xs">
            <button className="text-gray-700 hover:text-gray-900 border-b-2 border-gray-300 pb-2">Layout</button>
            <button className="text-gray-500 hover:text-gray-700 pb-2">Background</button>
            <button className="ml-auto p-1 text-gray-600 hover:bg-gray-100 rounded">
              <svg className="w-4 h-4" fill="currentColor" viewBox="0 0 24 24">
                <path d="M12 8c1.1 0 2-.9 2-2s-.9-2-2-2-2 .9-2 2 .9 2 2 2zm0 2c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2zm0 6c-1.1 0-2 .9-2 2s.9 2 2 2 2-.9 2-2-.9-2-2-2z" />
              </svg>
            </button>
          </div>

          {/* Timeline */}
          <Timeline />
        </div>

        {/* Right Panel - Sidebar (Properties, AI Tools, Layers) */}
        <Sidebar />
      </div>
    </div>
  );
}

export default Editor;

